name: ci

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: macos-14
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: 3.24.3

      - name: Install requirements
        run: brew install go meson ninja nasm make

      - name: Print tool versions
        run: gmake tool-versions

      - name: Determine version
        id: version
        run: |
          echo "VERSION=${short_date}" >> $GITHUB_ENV

      - name: Build
        run: |
          export VERSION=${{ steps.version.outputs.version }}
          make all

      - name: Create Github release
        if: ${{ github.event.inputs.github_release == 'true'}}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body: |
            **Workflow run**: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          files: |
            build/output/*.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
